
package fiap.scj.ws.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MinhaSaudeImp", targetNamespace = "http://soap.ws.scj.fiap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MinhaSaudeImp {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularImc", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.CalcularImc")
    @ResponseWrapper(localName = "calcularImcResponse", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.CalcularImcResponse")
    @Action(input = "http://soap.ws.scj.fiap/MinhaSaudeImp/calcularImcRequest", output = "http://soap.ws.scj.fiap/MinhaSaudeImp/calcularImcResponse")
    public double calcularImc(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resultadoIMC", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.ResultadoIMC")
    @ResponseWrapper(localName = "resultadoIMCResponse", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.ResultadoIMCResponse")
    @Action(input = "http://soap.ws.scj.fiap/MinhaSaudeImp/resultadoIMCRequest", output = "http://soap.ws.scj.fiap/MinhaSaudeImp/resultadoIMCResponse")
    public String resultadoIMC(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
